### ISSUE TITLE
[Suggestion] Immediate Respawn

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [ErikX-PMMP/AdvanceDeaths#1]
Add immediate respawn option. Like how [this](https://poggit.pmmp.io/p/FastRespawn/2.0.0) plugin does it. 
In the config...
immediate-respawn: false # Enable/disables immediate respawn. When you die it bypasses the death screen.

**Comment by ErikPDev** [comment]
Thanks for the suggestion! I'll add this feature soon!

**Comment by ErikPDev** [comment]
Immediate Respawn has been implemented to the lastest build.
Keep Inventory bug is also patched on the lastest build.

**Comment by ErikPDev** [comment]
This will be re-added when the translation update comes out.

**Comment by ErikPDev** [comment]
#4 Going to add it!

**Comment by ErikPDev** [comment]
@ZZWILLIAMXXTrue Just to update you, I’m no longer using that plug-in’s method because it’s outdated and buggy.
I’ve approached a new method I’ve discovered after reverse engineering the game rule command in Minecraft BDS Server.
